### ISSUE TITLE
View docs by gem version

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-rb.org#59]
A number of queries and confusion raised on the gitter room seem to be caused by people using the examples and guidance on the dry-rb site with an older version of a gem.

IMHO, a lot of this confusion could be addressed if it was easy to view the docs that relate to the version of the gem you are using. @timriley suggested something like [bundlers website](http://bundler.io/). 

The other benefits:
- we can update the site with changes on master as we go rather than holding off until a gem release.
- the history of the gem & its docs is easily accessible in the site.

**Comment by solnic** [comment]
This is obviously a great idea. And a big task :/

**Comment by fran-worley** [comment]
I appreciate that I've probably simplified this in my head but and this would ignore historic versions but:

Keep an actively updated set of docs for each gem which relate to the master branch.

When releasing a gem, copy master docs to a folder for that version. Job done!


On 28 Apr 2016, at 13:31, Piotr Solnica <notifications@github.com<mailto:notifications@github.com>> wrote:


This is obviously a great idea. And a big task :/

-

**Comment by solnic** [comment]
OK this is becoming really important to get done, otherwise it'll be hard to update docs at once prior releasing a gem. It would be awesome if we could come up with a solution and start updating docs for dry-v/t already :)

**Comment by mrbongiolo** [comment]
So those docs would live inside each projects and then just copy then to dry-rb site whenever a new version is released? Or what were you planning?

**Comment by solnic** [comment]
yeah we should have docs grouped by version with `head` docs being updated along with changes being made on master branches so that we can easily swap docs once new gem versions are released. Otherwise we may easily miss changes and forget about updating some parts of the docs.

**Comment by timriley** [comment]
@mrbongiolo I think we'd still keep all the docs inside the dry-rb.org repository, we'd just have a directory for each major version (e.g. `gems/dry-validation/0.7`, `gems/dry-validation/head`, etc.)

I'd imagine that we'd just copy/paste the previous version into a new one when we go to prepare new docs.

And then we'd need to build some middleman helpers to give us the kind of nav we want (and default to the latest non-head version of the docs for the "naked" URL).

**Comment by mrbongiolo** [comment]
So when we make a change we need to update `dry-validation` and dry-rb.org docs? Wouldn't it be better to have a `docs` folder on the project itself and we use it to update the dry-rb docs with each release?
Is there a way to make the examples on the docs `runnable`? So we would know if some of them breaks with a change.

**Comment by solnic** [comment]
It’s an interesting idea to store docs inside individual repos, the
drawback is that we’d have to somehow pull the docs into dry-rb.org repo
and keep that in sync, but this shouldn’t be too hard.


On 16 June 2016 at 15:32:28, Ralf Schmitz Bongiolo (notifications@github.com)
wrote:

So when we make a change we need to update dry-validation and dry-rb.org
docs? Wouldn't it be better to have a docs folder on the project itself and
we use it to update the dry-rb docs with each release?
Is there a way to make the examples on the docs runnable? So we would know
if some of them breaks with a change.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dry-rb/dry-rb.org/issues/59#issuecomment-226485633>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AAAEKt_abGrPh_etFNVAcK28O92YCc4Mks5qMVBogaJpZM4INlSM>
.

**Comment by flash-gordon** [comment]
We deployed initial support for this
